FROM openwrt/rootfs:x86_64-openwrt-24.10

# RUN mkdir -p /var/lock \
#   && mkdir -p /var/run \
#   && opkg update \
#   && opkg install \
#   luci \
#   luci-ssl \
#   luci-theme-openwrt \
#   && rm /var/opkg-lists/* \
#   && /etc/init.d/dropbear enable

CMD ["/bin/sh"]
